# Generated by Django 5.1.3 on 2025-11-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('telephone_whatsapp', models.CharField(help_text='Format: +212XXXXXXXXX ou 06XXXXXXXX', max_length=20, verbose_name='Numéro WhatsApp')),
                ('actif', models.BooleanField(default=True, help_text="Si désactivé, l'agent ne recevra plus de notifications", verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['nom'],
            },
        ),
    ]
