# Generated by Django 5.2.12 on 2026-03-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='telephone_whatsapp',
            field=models.CharField(help_text='Format international (ex: +2126XXXXXXXX ou 06XXXXXXXX)', max_length=20, verbose_name='Numéro de téléphone'),
        ),
    ]
