# Generated by Django 5.2.7 on 2025-10-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('assurance', 'Assurance'), ('visite', 'Visite Technique'), ('autorisation', 'Autorisation de Circulation'), ('entretien', 'Entretien')], max_length=50)),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_lue', models.BooleanField(default=False)),
                ('voiture', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
