# Generated by Django 5.1.3 on 2025-11-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='client_nom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='date_retour',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='urgence',
            field=models.BooleanField(default=False, help_text='Notification urgente avec son'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('assurance', 'Assurance'), ('visite', 'Visite Technique'), ('autorisation', 'Autorisation de Circulation'), ('entretien', 'Entretien'), ('retour_voiture', 'Retour de voiture')], max_length=50),
        ),
    ]
