# Generated by Django 5.2 on 2025-12-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('assurance', 'Assurance'), ('visite', 'Visite Technique'), ('autorisation', 'Autorisation de Circulation'), ('entretien', 'Entretien'), ('retour_voiture', 'Retour de voiture'), ('paiement', 'Rappel de paiement'), ('inscription_client', 'Inscription Client')], max_length=50),
        ),
    ]
