# Generated by Django 5.2.12 on 2026-03-30 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_type_add_reservation_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='whatsapp_date_envoi',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='whatsapp_envoye',
        ),
    ]
