"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from urllib.parse import urlparse, parse_qs
import os
import re
import socket

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

try:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
except ModuleNotFoundError:  # pragma: no cover - optional dependency
    sentry_sdk = None
    DjangoIntegration = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Charger les variables d'environnement depuis .env
load_dotenv(BASE_DIR / '.env')


def str_to_bool(value: str | None, default: bool = False) -> bool:
    if value is None:
        return default
    return value.lower() in {'1', 'true', 'yes', 'on'}


def str_to_list(value: str | None, default: str = '') -> list[str]:
    raw = value if value not in (None, '') else default
    return [item.strip() for item in raw.split(',') if item.strip()]


def dedupe(items: list[str]) -> list[str]:
    return list(dict.fromkeys(item for item in items if item))


def host_to_origin_regex(host: str) -> str | None:
    host = host.strip()
    if not host or host == '*':
        return None
    if host.startswith('http://') or host.startswith('https://'):
        return rf"^{re.escape(host)}$"

    allow_subdomains = host.startswith('.')
    trimmed = host.lstrip('.')
    if ':' in trimmed:
        hostname, port = trimmed.rsplit(':', 1)
        hostname_pattern = re.escape(hostname)
        return rf"^https?://{hostname_pattern}:{re.escape(port)}$"

    hostname_pattern = re.escape(trimmed)
    if allow_subdomains:
        hostname_pattern = rf"(?:[\w-]+\.)*{hostname_pattern}"
    return rf"^https?://{hostname_pattern}(?::\d+)?$"


def host_to_csrf_origins(host: str) -> list[str]:
    host = host.strip()
    if not host or host == '*':
        return []
    if host.startswith('http://') or host.startswith('https://'):
        return [host]

    allow_subdomains = host.startswith('.')
    trimmed = host.lstrip('.')
    prefix = '*.' if allow_subdomains else ''
    return [f"http://{prefix}{trimmed}", f"https://{prefix}{trimmed}"]


def get_local_ip_candidates() -> list[str]:
    ips: set[str] = set()
    for env_key in ('LOCAL_IP_ADDRESSES', 'SERVER_IP', 'HOST_IP'):
        ips.update(str_to_list(os.getenv(env_key)))
    try:
        hostname = socket.gethostname()
        if hostname:
            host_ip = socket.gethostbyname(hostname)
            if host_ip:
                ips.add(host_ip)
            for family in (socket.AF_INET,):
                try:
                    for info in socket.getaddrinfo(hostname, None, family=family):
                        ip_addr = info[4][0]
                        if ip_addr:
                            ips.add(ip_addr)
                except OSError:
                    continue
    except OSError:
        pass
    ips.discard('127.0.0.1')
    ips.discard('0.0.0.0')
    return sorted(ips)


def get_env_setting(
    name: str,
    default: str | None = None,
    *,
    required: bool = False,
) -> str | None:
    value = os.getenv(name)
    if value not in (None, ''):
        return value
    if required and default in (None, ''):
        raise ImproperlyConfigured(f"Missing required environment variable: {name}")
    return default


def parse_database_url(default_sqlite_path: Path) -> dict:
    db_url = os.getenv('DATABASE_URL')
    if not db_url:
        return {
            'ENGINE': 'django_prometheus.db.backends.sqlite3',
            'NAME': default_sqlite_path,
        }

    parsed = urlparse(db_url)
    scheme = parsed.scheme.replace('postgres', 'postgresql')
    engine_map = {
        'postgresql': 'django.db.backends.postgresql',
        'mysql': 'django.db.backends.mysql',
        'sqlite': 'django.db.backends.sqlite3',
    }
    engine = engine_map.get(scheme)
    if not engine:
        raise ImproperlyConfigured(
            f"Unsupported database scheme '{parsed.scheme}' in DATABASE_URL"
        )

    if engine.endswith('sqlite3'):
        db_name = parsed.path.lstrip('/') or default_sqlite_path
        return {'ENGINE': engine, 'NAME': db_name}

    db_config: dict[str, object] = {
        'ENGINE': engine,
        'NAME': parsed.path.lstrip('/') or '',
        'USER': parsed.username,
        'PASSWORD': parsed.password,
        'HOST': parsed.hostname,
        'PORT': parsed.port,
    }

    query_options = {
        key.upper(): values[0]
        for key, values in parse_qs(parsed.query).items()
        if values
    }
    if query_options:
        db_config['OPTIONS'] = query_options

    return db_config


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = str_to_bool(os.getenv('DEBUG'), False)

# SECURITY WARNING: keep the secret key used in production secret!
if DEBUG:
    SECRET_KEY = os.getenv(
        'DJANGO_SECRET_KEY',
        'django-insecure-dkoe@f)+=z0zzb_!($0w(vq&!hy4a5aw156u7n(8lig*fpszzs',
    )
else:
    SECRET_KEY = get_env_setting('DJANGO_SECRET_KEY', required=True)

ENVIRONMENT = os.getenv('ENVIRONMENT', 'development')

# Construire dynamiquement la liste des hôtes autorisés
_local_ip_candidates = get_local_ip_candidates()
_default_host_entries = dedupe(['localhost', '127.0.0.1', *_local_ip_candidates])
default_hosts = ','.join(_default_host_entries) if _default_host_entries else 'localhost,127.0.0.1'
ALLOWED_HOSTS = str_to_list(os.getenv('ALLOWED_HOSTS'), default_hosts)
if DEBUG and '*' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.insert(0, '*')
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost']
ALLOWED_HOSTS = dedupe(ALLOWED_HOSTS)

# URL secrète de l'admin (doit se terminer par /)
ADMIN_SECRET_PATH = os.getenv('ADMIN_SECRET_PATH', 'jet5-secure-panel-2026/').strip()
if ADMIN_SECRET_PATH.startswith('/'):
    ADMIN_SECRET_PATH = ADMIN_SECRET_PATH[1:]
if not ADMIN_SECRET_PATH.endswith('/'):
    ADMIN_SECRET_PATH = f"{ADMIN_SECRET_PATH}/"


# Application definition

INSTALLED_APPS = [
    'django_prometheus',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     # apps
    'accounts',
    'clients',
    'cars',
    'reservations',
    'payments',
    'notifications',
    'dashboard',

    # externes
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'axes',
]

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]


# ===========================================
# CORS Configuration - Simple and explicit
# ===========================================

# Allow all origins in development (set to False in production)
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'true').lower() == 'true' if DEBUG else False

# Explicit list of allowed origins (used when CORS_ALLOW_ALL_ORIGINS is False)
_default_cors_origins = [
    'https://locasolution.ma',
    'https://www.locasolution.ma',
]
CORS_ALLOWED_ORIGINS = dedupe(
    [s.strip() for s in str_to_list(os.getenv('CORS_ALLOWED_ORIGINS'))]
    + _default_cors_origins
)

# Allow credentials (cookies, authorization headers)
CORS_ALLOW_CREDENTIALS = os.getenv('CORS_ALLOW_CREDENTIALS', 'true').lower() == 'true'

# Allowed headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Allowed methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# CSRF trusted origins
_default_csrf_origins = [
    'http://localhost:3000',
    'https://locasolution.ma',
    'https://www.locasolution.ma',
]
CSRF_TRUSTED_ORIGINS = dedupe(
    str_to_list(os.getenv('CSRF_TRUSTED_ORIGINS')) + _default_csrf_origins
)



ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django_prometheus.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
     }
else:

    DATABASES = {
        'default': {
            'ENGINE': os.getenv('DB_ENGINE', 'django_prometheus.db.backends.mysql'), 
            'NAME': os.getenv('DB_NAME','jet5_db'),
            'USER': os.getenv('DB_USER','jet5_user'),
            'PASSWORD': os.getenv('DB_PASSWORD','jet5_password'),
            'HOST': os.getenv('DB_HOST','localhost'),
            'PORT': os.getenv('DB_PORT','3306'),
            'OPTIONS': {    
                'charset': 'utf8mb4',
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = os.getenv('STATIC_URL', '/static/')
STATIC_ROOT = Path(os.getenv('STATIC_ROOT', str(BASE_DIR / 'staticfiles')))

_default_static_dirs = [
    BASE_DIR / 'static',
    (BASE_DIR.parent / 'frontend' / 'dist') if (BASE_DIR.parent / 'frontend').exists() else None,
]
STATICFILES_DIRS = [path for path in _default_static_dirs if path and path.exists()]

# Media files (User uploads)
MEDIA_URL = os.getenv('MEDIA_URL', '/media/')
MEDIA_ROOT = Path(os.getenv('MEDIA_ROOT', str(BASE_DIR / 'media')))

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
        'LOCATION': str(MEDIA_ROOT),
    },
    'staticfiles': {
        'BACKEND': (
            'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
            if not DEBUG
            else 'django.contrib.staticfiles.storage.StaticFilesStorage'
        ),
        'LOCATION': str(STATIC_ROOT),
    },
}



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'backend.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': os.getenv('DRF_USER_THROTTLE', '1000/day'),
        'anon': os.getenv('DRF_ANON_THROTTLE', '100/day'),
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(
        minutes=int(os.getenv('JWT_ACCESS_MINUTES', '60'))
    ),
    'REFRESH_TOKEN_LIFETIME': timedelta(
        days=int(os.getenv('JWT_REFRESH_DAYS', '7'))
    ),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

AXES_ENABLED = str_to_bool(os.getenv('AXES_ENABLED'), not DEBUG)
AXES_FAILURE_LIMIT = int(os.getenv('AXES_FAILURE_LIMIT', '5'))
AXES_COOLOFF_TIME = timedelta(
    minutes=int(os.getenv('AXES_COOLOFF_MINUTES', '30'))
)
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_PARAMETERS = ['username', 'ip_address']

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

if AXES_ENABLED:
    AUTHENTICATION_BACKENDS.insert(0, 'axes.backends.AxesBackend')

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
]

SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Strict' if not DEBUG else 'Lax'
SESSION_COOKIE_AGE = int(os.getenv('SESSION_COOKIE_AGE', 60 * 60 * 24 * 14))

CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Strict' if not DEBUG else 'Lax'
CSRF_USE_SESSIONS = True

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
SECURE_SSL_REDIRECT = str_to_bool(
    os.getenv('SECURE_SSL_REDIRECT'),
    not DEBUG,
)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
X_FRAME_OPTIONS = 'DENY'
USE_X_FORWARDED_HOST = str_to_bool(os.getenv('USE_X_FORWARDED_HOST'), not DEBUG)

DATA_UPLOAD_MAX_MEMORY_SIZE = int(
    os.getenv('DATA_UPLOAD_MAX_MEMORY_SIZE', 10 * 1024 * 1024)
)
FILE_UPLOAD_MAX_MEMORY_SIZE = int(
    os.getenv('FILE_UPLOAD_MAX_MEMORY_SIZE', 10 * 1024 * 1024)
)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            'format': '{"timestamp":"%(asctime)s","level":"%(levelname)s","name":"%(name)s","message":"%(message)s"}',
            'datefmt': '%Y-%m-%dT%H:%M:%S%z',
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'json',
        }
    },
    'root': {
        'handlers': ['console'],
        'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
    },
    'loggers': {
        'notifications.apps': {
            'level': 'WARNING',
            'handlers': ['console'],
            'propagate': False,
        },
        'axes.apps': {
            'level': 'WARNING',
            'handlers': ['console'],
            'propagate': False,
        },
        'django.utils.autoreload': {
            'level': 'WARNING',
            'handlers': ['console'],
            'propagate': False,
        },
    },
}

PROMETHEUS_EXPORT_MIGRATIONS = False

SENTRY_DSN = os.getenv('SENTRY_DSN')
SENTRY_TRACES_SAMPLE_RATE = float(os.getenv('SENTRY_TRACES_SAMPLE_RATE', '0.0'))

START_NOTIFICATION_SCHEDULER = str_to_bool(
    os.getenv('START_NOTIFICATION_SCHEDULER'),
    not DEBUG,
)

if SENTRY_DSN and sentry_sdk and DjangoIntegration:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        traces_sample_rate=SENTRY_TRACES_SAMPLE_RATE,
        send_default_pii=False,
        environment=ENVIRONMENT,
    )



