# Generated by Django 5.1.3 on 2025-10-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratlocation',
            name='nombre_jours',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Nombre de jours de location', null=True),
        ),
        migrations.AlterField(
            model_name='contratlocation',
            name='caution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='contratlocation',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contratlocation',
            name='montant_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='contratlocation',
            name='prix_journalier',
            field=models.DecimalField(decimal_places=2, help_text='Prix par jour', max_digits=10),
        ),
    ]
