# Generated by Django 5.1.3 on 2025-11-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_contratlocation_nombre_jours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratlocation',
            name='caution',
        ),
        migrations.AddField(
            model_name='contratlocation',
            name='avance',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Montant de l'avance payée", max_digits=12),
        ),
    ]
