# Generated by Django 5.1.3 on 2025-11-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_remove_contratlocation_caution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratlocation',
            name='caution',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant de la caution', max_digits=12),
        ),
    ]
