# Generated by Django 5.1.3 on 2025-11-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_contratlocation_caution'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratlocation',
            name='methode_paiement',
            field=models.CharField(choices=[('CASH', 'Espèces'), ('CARD', 'Carte'), ('CHEQUE', 'Chèque'), ('TPE', 'TPE'), ('TRANSFER', 'Virement'), ('OTHER', 'Autre')], default='CASH', help_text="Méthode de paiement pour l'avance", max_length=20),
        ),
    ]
