# Generated by Django 5.1.3 on 2025-11-07 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_cin_document_client_passeport_document_and_more'),
        ('reservations', '0005_contratlocation_methode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratlocation',
            name='conducteur_secondaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_as_secondary_driver', to='clients.client', verbose_name='Conducteur Secondaire'),
        ),
    ]
