# Generated by Django 5.1.3 on 2025-11-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_add_archive_delete_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratlocation',
            name='jours_prolongation',
            field=models.PositiveIntegerField(blank=True, default=0, help_text="Jours d'extension de location"),
        ),
        migrations.AlterField(
            model_name='contratlocation',
            name='statut',
            field=models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_cours', max_length=20),
        ),
    ]
