# Generated by Django 5.2 on 2025-12-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_contratlocation_jours_prolongation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratlocation',
            name='franchise',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant de la franchise', max_digits=12),
        ),
    ]
