# Generated by Django 5.2 on 2025-12-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_contratlocation_franchise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratlocation',
            name='caution',
        ),
    ]
