# Generated by Django 5.2.9 on 2026-01-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_add_numero_contrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratlocation',
            name='tarif_special',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant total personnalisé (écrase le calcul automatique)', max_digits=12, null=True),
        ),
    ]
