# Generated by Django 5.2.9 on 2026-01-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_contratlocation_tarif_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratlocation',
            name='heure_depart',
            field=models.TimeField(blank=True, help_text='Heure de départ/location', null=True),
        ),
        migrations.AddField(
            model_name='contratlocation',
            name='heure_retour',
            field=models.TimeField(blank=True, help_text='Heure de retour/récupération', null=True),
        ),
    ]
