# Generated by Copilot
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_contratlocation_heure_depart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratlocation',
            name='billing_mode',
            field=models.CharField(choices=[('JOURNALIER', 'Journalier'), ('FORFAIT', 'Forfait')], default='JOURNALIER', help_text='Mode de facturation (journalier ou forfait)', max_length=20),
        ),
        migrations.AddField(
            model_name='contratlocation',
            name='long_duration',
            field=models.BooleanField(default=False, help_text='Contrat longue durée (date de fin facultative)'),
        ),
    ]
