# Generated by Django 5.2.9 on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_contratlocation_dropoff_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratlocation',
            name='tarif_special_unite',
            field=models.CharField(choices=[('SEMAINE', 'Par semaine'), ('MOIS', 'Par mois')], default='MOIS', help_text='Unité du tarif spécial (par semaine ou par mois)', max_length=20),
        ),
    ]
