# Generated by Django 5.2.7 on 2025-10-27 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('immatriculation', models.CharField(max_length=50, unique=True)),
                ('kilometrage', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('libre', 'Libre'), ('louee', 'Louée'), ('entretien', 'En entretien'), ('hors_service', 'Hors service')], default='libre', max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisiteTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateField()),
                ('date_expiration', models.DateField()),
                ('valide', models.BooleanField(default=True)),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites_techniques', to='cars.voiture')),
            ],
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=150)),
                ('cout', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_entretien', models.CharField(max_length=150)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='cars.voiture')),
            ],
        ),
        migrations.CreateModel(
            name='AutorisationCirculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_delivrance', models.DateField()),
                ('date_expiration', models.DateField()),
                ('valide', models.BooleanField(default=True)),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorisations_circulation', to='cars.voiture')),
            ],
        ),
        migrations.CreateModel(
            name='Assurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('valide', models.BooleanField(default=True)),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assurances', to='cars.voiture')),
            ],
        ),
    ]
