# Generated by Django 5.2 on 2025-10-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assurance',
            old_name='date_fin',
            new_name='date_expiration',
        ),
    ]
