# Generated by Django 5.1.3 on 2025-10-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_date_fin_assurance_date_expiration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entretien',
            old_name='date_debut',
            new_name='date_entretien',
        ),
        migrations.RenameField(
            model_name='entretien',
            old_name='date_fin',
            new_name='prochain_entretien',
        ),
        migrations.RemoveField(
            model_name='entretien',
            name='lieu',
        ),
        migrations.AddField(
            model_name='assurance',
            name='alerte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='autorisationcirculation',
            name='alerte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitetechnique',
            name='alerte',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='type_entretien',
            field=models.CharField(choices=[('vidange', 'Vidange'), ('pneus', 'Changement de pneus'), ('freins', 'Révision des freins'), ('batterie', 'Batterie'), ('autre', 'Autre')], max_length=100),
        ),
    ]
