# Generated by Django 5.1.3 on 2025-11-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_date_debut_entretien_date_entretien_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='prix_journalier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
