# Generated by Django 5.1.3 on 2025-11-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_voiture_prix_journalier'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='couleur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
