# Generated by Django 5.1.3 on 2025-11-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_voiture_couleur'),
    ]

    operations = [
        migrations.AddField(
            model_name='assurance',
            name='compagnie',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assurance',
            name='document_pdf',
            field=models.FileField(blank=True, null=True, upload_to='assurances/'),
        ),
        migrations.AddField(
            model_name='assurance',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='assurance',
            name='numero_contrat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
