# Generated by Django 5.1.3 on 2025-11-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_assurance_compagnie_assurance_document_pdf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entretien',
            options={'ordering': ['-date_entretien']},
        ),
        migrations.AddField(
            model_name='entretien',
            name='alerte_avance_jours',
            field=models.PositiveIntegerField(default=30, help_text="Alerte X jours avant l'échéance"),
        ),
        migrations.AddField(
            model_name='entretien',
            name='alerte_avance_km',
            field=models.PositiveIntegerField(default=1000, help_text="Alerte X km avant l'échéance"),
        ),
        migrations.AddField(
            model_name='entretien',
            name='description',
            field=models.TextField(blank=True, help_text="Description ou notes sur l'entretien", null=True),
        ),
        migrations.AddField(
            model_name='entretien',
            name='intervalle_kilometrage',
            field=models.PositiveIntegerField(blank=True, help_text='Intervalle en km pour le prochain entretien', null=True),
        ),
        migrations.AddField(
            model_name='entretien',
            name='intervalle_mois',
            field=models.PositiveIntegerField(blank=True, help_text='Intervalle en mois pour le prochain entretien', null=True),
        ),
        migrations.AddField(
            model_name='entretien',
            name='kilometrage_actuel_voiture',
            field=models.PositiveIntegerField(default=0, help_text="Kilométrage de la voiture au moment de l'entretien"),
        ),
        migrations.AddField(
            model_name='entretien',
            name='statut_entretien',
            field=models.CharField(choices=[('a_venir', 'À venir'), ('urgent', 'Urgent'), ('effectue', 'Effectué'), ('en_retard', 'En retard')], default='a_venir', max_length=20),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='prochain_entretien',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='type_entretien',
            field=models.CharField(choices=[('vidange', 'Vidange'), ('pneus', 'Changement de pneus'), ('freins', 'Révision des freins'), ('batterie', 'Batterie'), ('filtre_air', 'Filtre à air'), ('filtre_carburant', 'Filtre à carburant'), ('courroie', 'Courroie de distribution'), ('climatisation', 'Climatisation'), ('controle_general', 'Contrôle général'), ('autre', 'Autre')], max_length=100),
        ),
    ]
