# Generated by Django 5.1.3 on 2025-11-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_add_entretien_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitetechnique',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
