# Generated by Django 5.1.3 on 2025-12-04 10:16

from django.db import migrations


def _ensure_prix_total(apps, schema_editor):
    EntretienVidange = apps.get_model('cars', 'EntretienVidange')
    for vidange in EntretienVidange.objects.filter(prix_total__isnull=True):
        vidange.prix_total = 0
        vidange.save(update_fields=['prix_total'])


def _noop_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_sync_vidange_prix_total'),
    ]

    operations = [
        migrations.RunPython(_ensure_prix_total, _noop_backward),
    ]
