# Generated by Django 5.2.9 on 2026-01-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_add_prix_total_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='annee',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Année'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='carburant',
            field=models.CharField(blank=True, choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('hybride', 'Hybride'), ('electrique', 'Électrique'), ('gpl', 'GPL')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voiture',
            name='categorie',
            field=models.CharField(blank=True, choices=[('economique', 'Économique'), ('berline', 'Berline'), ('suv', 'SUV'), ('luxe', 'Luxe'), ('utilitaire', 'Utilitaire'), ('familiale', 'Familiale')], max_length=50, null=True, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='dernier_entretien',
            field=models.DateField(blank=True, null=True, verbose_name='Dernier entretien'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='franchise',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Franchise'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='numero_chassis',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de châssis'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='places',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de places'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='portes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de portes'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='prix_achat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Prix d'achat"),
        ),
        migrations.AddField(
            model_name='voiture',
            name='prochain_entretien',
            field=models.DateField(blank=True, null=True, verbose_name='Prochain entretien'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='proprietaire',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Propriétaire'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='transmission',
            field=models.CharField(blank=True, choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='prix_journalier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix journalier'),
        ),
    ]
