# Generated by Django 5.2.9 on 2026-01-22 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_voiture_annee_voiture_carburant_voiture_categorie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='franchise',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='numero_chassis',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='places',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='portes',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='prix_achat',
        ),
        migrations.RemoveField(
            model_name='voiture',
            name='proprietaire',
        ),
    ]
