# Generated by Django 5.2.12 on 2026-03-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_remove_voiture_franchise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='image_principale',
            field=models.ImageField(blank=True, help_text='Image principale utilisée sur le site public', null=True, upload_to='cars/'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Si activé, la voiture sera affichée sur le site public'),
        ),
    ]
