# Generated by Django 5.2.12 on 2026-03-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_voiture_image_principale_voiture_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoitureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/gallery/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('voiture', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='images', to='cars.voiture')),
            ],
            options={
                'ordering': ['date_ajout'],
            },
        ),
    ]