# Generated by Django 5.2.12 on 2026-03-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_voitureimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='description',
            field=models.TextField(blank=True, help_text='Description du véhicule affichée sur le site public', null=True),
        ),
    ]
