# Generated by Django 5.2.12 on 2026-03-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_voiture_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='equipements',
            field=models.TextField(blank=True, help_text='Équipements séparés par des virgules (ex: GPS intégré, Caméra 360°, Climatisation)', null=True),
        ),
        migrations.AddField(
            model_name='voiture',
            name='nombre_places',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de places'),
        ),
    ]
