# Generated by Django 5.2.7 on 2025-10-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('cin_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('cin_date_expiration', models.DateField(blank=True, null=True)),
                ('permis_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('permis_date_delivrance', models.DateField(blank=True, null=True)),
                ('passeport_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('passeport_date_entree', models.DateField(blank=True, null=True)),
                ('passeport_date_sortie', models.DateField(blank=True, null=True)),
                ('est_archive', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
