# Generated by Django 5.1.3 on 2025-11-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cin_document',
            field=models.FileField(blank=True, null=True, upload_to='clients/cin/'),
        ),
        migrations.AddField(
            model_name='client',
            name='passeport_document',
            field=models.FileField(blank=True, null=True, upload_to='clients/passeport/'),
        ),
        migrations.AddField(
            model_name='client',
            name='permis_document',
            field=models.FileField(blank=True, null=True, upload_to='clients/permis/'),
        ),
    ]
