# Generated by Django 5.2 on 2025-12-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('cin_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('cin_date_expiration', models.DateField(blank=True, null=True)),
                ('permis_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('permis_date_delivrance', models.DateField(blank=True, null=True)),
                ('passeport_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('passeport_date_entree', models.DateField(blank=True, null=True)),
                ('passeport_date_sortie', models.DateField(blank=True, null=True)),
                ('cin_document', models.FileField(blank=True, null=True, upload_to='client_requests/cin/')),
                ('permis_document', models.FileField(blank=True, null=True, upload_to='client_requests/permis/')),
                ('passeport_document', models.FileField(blank=True, null=True, upload_to='client_requests/passeport/')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé')], default='pending', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Demande d'inscription",
                'verbose_name_plural': "Demandes d'inscription",
                'ordering': ['-date_creation'],
            },
        ),
    ]
