# Generated by Django 5.1.3 on 2025-10-31 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('reservations', '0002_contratlocation_nombre_jours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('espece', 'Espèces'), ('carte', 'Carte Bancaire'), ('virement', 'Virement')], max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(default='Payé', max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='clients.client')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='reservations.contratlocation')),
            ],
        ),
    ]
