# Generated by Django 5.1.3 on 2025-10-31 14:37

import django.core.validators
import django.db.models.deletion
import payments.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('reservations', '0002_contratlocation_nombre_jours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('method', models.CharField(choices=[('CASH', 'Espèces'), ('CARD', 'Carte'), ('TRANSFER', 'Virement'), ('OTHER', 'Autre')], default='CARD', max_length=20)),
                ('status', models.CharField(choices=[('PAID', 'Payé'), ('PENDING', 'En attente'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to=payments.models.invoice_upload_to)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='reservations.contratlocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Paiement',
        ),
    ]
