# Generated by Django 5.1.3 on 2025-11-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='client_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='client_name',
            field=models.CharField(blank=True, max_length=201, null=True),
        ),
    ]
