# Generated by Django 5.1.3 on 2025-11-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_paymenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Espèces'), ('CARD', 'Carte'), ('CHEQUE', 'Chèque'), ('TPE', 'TPE'), ('TRANSFER', 'Virement'), ('OTHER', 'Autre')], default='CARD', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='method',
            field=models.CharField(choices=[('CASH', 'Espèces'), ('CARD', 'Carte'), ('CHEQUE', 'Chèque'), ('TPE', 'TPE'), ('TRANSFER', 'Virement'), ('OTHER', 'Autre')], max_length=20),
        ),
    ]
