# Generated by Django 5.1.3 on 2025-11-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_payment_method_alter_paymenthistory_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Date de suppression', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Paiement supprimé (corbeille)'),
        ),
    ]
