# Generated by Django 5.1.3 on 2025-11-21 10:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_payment_deleted_at_payment_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='forgiven_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant pardonné/remise accordée', max_digits=12),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='forgiven_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant pardonné pour cette transaction', max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
