# Generated by Django 5.2.9 on 2026-03-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_payment_forgiven_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='monthly_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant fixe attendu par mois pour ventiler les encaissements (longue durée)', max_digits=12, null=True),
        ),
    ]
